### PR TITLE
fix up qkv.bias error when use qwen1.5-32b-gptq-int4

### PR DESCRIPTION
**Pull request by Tlntin**

### CODE REVIEW

**Comment by byshiue** [comment]
Thank you for the report. Could you share the model link to reproduce the issue?

**Comment by Tlntin** [comment]
> Thank you for the report. Could you share the model link to reproduce the issue?

[model link](https://huggingface.co/Qwen/Qwen1.5-32B-Chat-GPTQ-Int4)

**Comment by byshiue** [comment]
Thank you for the sharing. I can reproduce the issue on the model, will fix it soon.

**Comment by nv-guomingz** [comment]
Hi @Tlntin, thanks for your contributing. We've merged your contribution into code base and will add you into contributor list.

**Pull request closed without merging**
