### PR TITLE
Update TensorRT-LLM

### PR DESCRIPTION
**Pull request by kaiyux**
* Model Support
  - RoBERTa support (thanks to the contribution from @erenup)
* Features
  - Chunked context support (see docs/source/gpt_attention.md#chunked-context)
* API
  - Migrate models to the new build workflow, including LLaMA, Mistral, Mixtral, InternLM, ChatGLM, Falcon, GPT-J, GPT-NeoX, Medusa, MPT, Baichuan and Phi.
  - Deprecate `LayerNorm` and `RMSNorm` plugins
  - High-level-API: Support multi-GPU Tensor Parallelism on the `LLM.generate_async` API
* Bug fixes
  - Fix INT8 GEMM shape #935

### CODE REVIEW

**Review by Shixiaowei02 — APPROVED** [review]

**Comment by enochlev** [comment]
Thank you for the update!!!

We cam across a few questions

Are these argument now deprecated?
--use_inflight_batching


More specifically, how much is changed from this tutorial
https://developer.nvidia.com/blog/optimizing-inference-on-llms-with-tensorrt-llm-now-publicly-available/ 

Thank You

**Comment by 827346462** [comment]
i Run example/blip2 .Is the project missing convert_checkpoint.py files

**Comment by kaiyux** [comment]
> Are these argument now deprecated? --use_inflight_batching

@enochlev Yes, the argument `--use_inflight_batching` was identical to `--use_gpt_attention_plugin --use_paged_kv_cache --remove_input_padding` in the previous version, for now, you can still enable inflight batching by enabling those three features, and note that they are enabled by default. 

Please see the updated [document](https://gitlab-master.nvidia.com/ftp/tekit#quick-start), and use `trtllm-build --help` to get full help information. Thanks.

**Comment by kaiyux** [comment]
> i Run example/blip2 .Is the project missing convert_checkpoint.py files

Hi @827346462 Please take a look and follow the [document](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/blip2#guide-to-blip-2-pipeline) of `blip2`, we do not need `convert_checkpoint.py` for that model, thanks.

**Comment by 827346462** [comment]
> > i Run example/blip2 .Is the project missing convert_checkpoint.py files
> 
> Hi @827346462 Please take a look and follow the [document](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/blip2#guide-to-blip-2-pipeline) of , we do not need for that model, thanks.`blip2``convert_checkpoint.py`

follow the [https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/blip2#guide-to-blip-2-pipeline ](url) "python3 convert_checkpoint.py --model_dir ./opt-2.7b \
            --dtype float16 \
            --output_dir ./opt/2.7B/trt_ckpt/fp16/1-gpu/"， in project no convert_checkpoint.py

**Pull request merged**
