### PR TITLE
Update TensorRT-LLM

### PR DESCRIPTION
**Pull request by kaiyux**
* Model Support
  - Mixture of Experts support
* Features
  - fMHA support for chunked attention and paged kv cache
  - Baichuan FP8 quantization support
* Memory optimization
  - Reduced host memory when building engines
* Performance
  - MMHA optimization for MQA and GQA

### CODE REVIEW

**Comment by EwoutH** [comment]
Only two million lines of code changes, very comprehensible and reviewable!

Good luck @Shixiaowei02, you can do this!

**Review by Shixiaowei02 — APPROVED** [review]

**Comment by explainerauthors** [comment]
My guess is that the NVIDIA team has been working on an internal repo. And periodically, they release their code into this repo on GitHub.

**Comment by Shixiaowei02** [comment]
> My guess is that the NVIDIA team has been working on an internal repo. And periodically, they release their code into this repo on GitHub.

Exactly, thanks for your explanation! @explainerauthors

**Comment by fishbone** [comment]
@kaiyux can you share more detail about __chunked attention__ mentioned in the description?

**Comment by juney-nvidia** [comment]
> @kaiyux can you share more detail about **chunked attention** mentioned in the description?

Pls refer [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/gpt_attention.md#sliding-window-attention-cyclic-rolling-buffer-kv-cache). The chunked attention here is for the generation phase.

**Pull request merged**
