### PR TITLE
add support internvl2

### PR DESCRIPTION
**Pull request by Jeremy-J-J**
add support internvl2

### CODE REVIEW

**Comment by nv-guomingz** [comment]
Thanks @Jeremy-J-J for your contribution,
I just checked the doc on examples/multimodal and it seems this kind of model had been supported yet.

**Comment by Jeremy-J-J** [comment]
> Thanks @Jeremy-J-J for your contribution, I just checked the doc on examples/multimodal and it seems this kind of model had been supported yet.
> 

It seems I don’t have permission to access this website. Has it been released already? The latest main branch doesn’t seem to have it yet, refef to [main/examples/mulitmoda](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal)

**Comment by nv-guomingz** [comment]
Hi @Jeremy-J-J , this model was just introduced into our internal code base a week ago, so it's not appear on the public main branch now.
I suggest you can have a try on coming weekly release and check this feature is good for your requirement.

B.T.W, I updated your message for protecting internal information.

**Comment by nv-guomingz** [comment]
https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#internvl2 @Jeremy-J-J

**Comment by Jeremy-J-J** [comment]
> https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#internvl2 @Jeremy-J-J

I see. Good job ! @nv-guomingz

**Comment by hchings** [comment]
Closing this out as internvl2 has been supported.

**Pull request closed without merging**
