### PR TITLE
Support custom calibration datasets

### PR DESCRIPTION
**Pull request by DreamGenX**
With this change, the user can supply a custom `json` or `jsonl`  with a `text` column for calibration.

### CODE REVIEW

**Comment by nv-guomingz** [comment]
Hi @syuoni ,would u please review this PR?

**Comment by syuoni** [comment]
Thanks @DreamGenX . I've started to integrate this PR to our internal repo, and probably this will be available in the next Github weekly update.

**Comment by DreamGenX** [comment]
Thank you @syuoni -- I just noticed it should also be probably added for the nemo codepath.

**Comment by syuoni** [comment]
Hi @DreamGenX , this PR is using `dataset_name_or_dir` as a single data file path, and supports json/jsonl only. 

An more general way is to prepare a HF dataset repo (according to [this instruction](https://huggingface.co/docs/datasets/main/en/repository_structure)), and use the local path to this repo for calibration. This allows more complex data structures (e.g., multiple files) and formats (e.g., csv). Does this make sense to you?

**Comment by syuoni** [comment]
> Thank you @syuoni -- I just noticed it should also be probably added for the nemo codepath.

Yes, I will cover the nemo path. Thanks for the reminder.

**Comment by syuoni** [comment]
> Hi @DreamGenX , this PR is using `dataset_name_or_dir` as a single data file path, and supports json/jsonl only.
> 
> An more general way is to prepare a HF dataset repo (according to [this instruction](https://huggingface.co/docs/datasets/main/en/repository_structure)), and use the local path to this repo for calibration. This allows more complex data structures (e.g., multiple files) and formats (e.g., csv). Does this make sense to you?

Hi @DreamGenX , We will go with this HF repo style support for customized calibration dataset. 

If you have a data file `path/to/data.json` that you want to pass to `dataset_name_or_dir`, you can just:
* move it to a separate folder and rename like `path/to/repo/train.json`, then 
* pass `path/to/repo` to `dataset_name_or_dir`.

**Pull request closed without merging**
